{
 "title": "NestJS Prometheus Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP Requests Total",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Request Duration P95",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[1m]))"
    }
   ]
  },
  {
   "title": "Heap Used (MB)",
   "type": "stat",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_used_bytes / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Event Loop Lag (s)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 5, "w": 8, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds" }
   ]
  },
  {
   "title": "Memory RSS (MB)",
   "type": "stat",
   "gridPos": { "x": 8, "y": 5, "w": 8, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nodejs_memory_rss_bytes / 1024 / 1024"
    }
   ]
  }
 ]
}