{
 "title": "Node.js - System Metrics",
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Heap Used (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nodejs_heap_used_bytes / 1024 / 1024",
     "legendFormat": "Heap Used"
    }
   ]
  },
  {
   "title": "Resident Set Size (RSS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes / 1024 / 1024",
     "legendFormat": "RSS"
    }
   ]
  },
  {
   "title": "Garbage Collection Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_sum[5m])",
     "legendFormat": "GC Duration"
    }
   ]
  }
 ]
}