{
 "title": "PostgreSQL - DB Stats",
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{state=\"active\"}",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(sum(rate(pg_stat_database_blks_hit[5m])) by (datname)) / (sum(rate(pg_stat_database_blks_hit[5m]) + rate(pg_stat_database_blks_read[5m])) by (datname))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Disk Read (blocks/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_read[1m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Transactions Committed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit[1m])",
     "legendFormat": "{{datname}}"
    }
   ]
  }
 ]
}