global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'nestjs'
    metrics_path: /metrics
    static_configs:
      - targets:
          [
            'nestjs_app_1:3000',
            'nestjs_app_2:3000',
            'nestjs_app_3:3000',
            'nestjs_app_4:3000',
            'nginx_lb:8000',
          ]

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
